non-mask:
    face_detection: face_detection_1.0
    face_alignment: face_alignment_1.0
    face_liveness: face_liveness_deepixbis
    face_recognition: face_recognition_arcface
mask:
    face_detection: face_detection_2.0
    face_alignment: face_alignment_2.0
    face_recognition: face_recognition_2.0
    